### ISSUE TITLE
[tracking] Add default logger to MLJ

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJ.jl#1124]
Further to resolving https://github.com/JuliaAI/MLJBase.jl/issues/926:

- [x]  https://github.com/JuliaAI/MLJBase.jl/pull/979
- [x] https://github.com/JuliaAI/MLJTuning.jl/pull/221
- [x] get MLJ to re-export `MLJBase.default_logger`, including new minimum [compat] bounds for MLJTuning, MLJBase; and tag the new release as version 0.21 (?). Update the MLJ manual to include the docstring for `default_logger`.
